# Generated by Django 4.2.4 on 2023-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(max_length=25)),
                ('objectCategory', models.CharField(max_length=6)),
                ('objectImage', models.ImageField(upload_to='objectImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=500)),
                ('placeImage', models.ImageField(upload_to='placeImages/')),
                ('placeCategory', models.CharField(max_length=6)),
            ],
        ),
    ]
