# Generated by Django 4.2.4 on 2023-11-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0002_object_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='objectImage',
            field=models.ImageField(upload_to='VATA_mainApp\\static\\VATA_mainApp\\ObjectImages'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeImage',
            field=models.ImageField(upload_to='VATA_mainApp\\static\\VATA_mainApp\\PlaceImages'),
        ),
    ]
