# Generated by Django 4.2.7 on 2023-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0003_alter_object_objectimage_alter_place_placeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
