# Generated by Django 4.2.7 on 2023-11-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0004_centroreciclaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentroReciclaje',
        ),
    ]
