# Generated by Django 4.2.7 on 2023-11-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0005_delete_centroreciclaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeImage',
            field=models.ImageField(blank=True, null=True, upload_to='VATA_mainApp\\static\\VATA_mainApp\\PlaceImages'),
        ),
    ]
