# Generated by Django 4.2.7 on 2023-11-28 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VATA_mainApp', '0006_alter_place_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
